#!/usr/bin/env python
"""setup_env.py — interactive setup of the optional .env (Telegram).

Telegram notifications are OPTIONAL; the pipeline runs fully without them. When
configured, run_det.py / batch_run_det.py send live start/finish/error messages,
handy for monitoring the training grid on the remote workstation.

Values are written to .env at the repo root (gitignored). Usage:
    python setup_env.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
KEYS = ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"]


def read_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def write_env(path: Path, env: dict[str, str]) -> None:
    lines = ["# Optional Telegram credentials for run notifications.",
             "# Generated by setup_env.py. Do not commit (gitignored).", ""]
    lines += [f"{k}={env[k]}" for k in KEYS if env.get(k)]
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    env = read_env(ENV_PATH)
    print("Optional Telegram setup (leave blank to keep current / skip).")
    for k in KEYS:
        cur = env.get(k, "")
        shown = f" [{cur[:6]}...]" if cur else ""
        val = input(f"{k}{shown}: ").strip()
        if val:
            env[k] = val
    write_env(ENV_PATH, env)
    ready = all(env.get(k) for k in KEYS)
    print(f"-> {ENV_PATH}  ({'configured' if ready else 'incomplete — notifications disabled'})")


if __name__ == "__main__":
    main()
